name: Daily Naukri Resume Upload2

on:
  schedule:
    - cron: "30 2 * * *"   # Runs every day at 08:00 AM IST (02:30 UTC)
  workflow_dispatch:        # Allows manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install playwright
          python -m playwright install chromium

      - name: Run Naukri Resume Upload Script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          RESUME1: ${{ secrets.RESUME1 }}
          RESUME2: ${{ secrets.RESUME2 }}
        run: python naukri_update.py
